#!/bin/sh

args=()
mode=prod
serve=0

if [ "$1" = "serve" ]; then
	serve=1
fi

for arg in $@; do
	if [ "$arg" = "-d" ] || [ "$arg" = "--dev" ]; then
		mode=dev
	else
		args+=($arg)
	fi
done

cmd="deno run \
	--allow-net \
	--allow-env \
	--allow-read=./ \
	--allow-write=data.db,data.db-journal \
	--unstable"

if [ "$mode" = "dev" ]; then
	if [ "$serve" ]; then
		echo "Enabling watch mode"
		cmd="$cmd --watch --allow-run=touch"
	fi
	cmd="$cmd --no-check=remote"
	echo "Using dev import map"
	export SC_IMPORT_MAP="import_map_dev.json"
else
	cmd="$cmd --no-check"
	export SC_IMPORT_MAP="import_map.json"
fi

$cmd --import-map ./$SC_IMPORT_MAP mod.ts ${args[@]}
