name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install firebase
        run: npm install -g firebase-cli
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pnpm install
      - name: Deploy
        run: pnpm deploy --token "$FIREBASE_TOKEN"
