name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-set@v1.2.1
        with:
          version: 5.13.1
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pnpm install
      - name: Deploy
        run: pnpm deploy --token "$FIREBASE_TOKEN"
